[package]
name = "rodal_asm_loader"
version = "0.0.1"
authors = [ "Your name <you@example.com>" ]
include = ["Cargo.toml", "src/**/*.rs"]

[dependencies]
libc = "0.2.24"
rodal = { version = "0.0.1", path = "../../rodal" }